application: aaco-events-hrd
version: 3
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin/
  login: admin

- url: /events/.*
  script: servlets/events.py
  login: required

- url: /s/.*
  script: servlets/website.py

- url: /published
  script: servlets/events.py
